// automatically generated by spin2cpp v3.9.27-beta-2f18e78b on Wed May 22 09:28:28 2019
// command line: /home/ersmith/Parallax/spin2cpp/build/spin2cpp --p2 --ccode BufferSerial.spin2 

#ifndef BufferSerial_Class_Defined__
#define BufferSerial_Class_Defined__

#include <stdint.h>

#define BUFFERSERIAL_RX_PIN (63)

typedef struct BufferSerial {
  volatile int32_t 	cog;
  volatile int32_t 	data;
} BufferSerial;

  int32_t BufferSerial_start(BufferSerial *self);
  int32_t BufferSerial_rx(BufferSerial *self);
#endif
