// automatically generated by spin2cpp v3.9.34-beta-1ac35f0e on Wed Oct  2 15:06:56 2019
// command line: /home/ersmith/Parallax/spin2cpp/build/spin2cpp -I.. --p2 --ccode vgatext.spin 

#ifndef vga_tile_driver_Class_Defined__
#define vga_tile_driver_Class_Defined__

#include <stdint.h>

// 0..128
#define VGA_TILE_DRIVER_INTENSITY (80)
#define VGA_TILE_DRIVER_PIXSHIFT (31)

typedef struct vga_tile_driver {
  int32_t 	mycog;
  int32_t 	hw_rev;
} vga_tile_driver;

  int32_t vga_tile_driver_start(vga_tile_driver *self, int32_t params);
  void vga_tile_driver_stop(vga_tile_driver *self);
  int32_t vga_tile_driver_calcscale(int32_t a, int32_t b);
#endif
